### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by josephmancuso** [josephmancuso/masonite#23]
- [x] Choose a cool name!

- [x] Create a description for your project.

- [x] Add a README.md file containing all the basic information about your project.

- [x] Create a CONTRIBUTING.md file containing all the necessary information so that other developers can help you.

- [x] Add a .gitignore file containing everything you do not want versioning .

- [x] Select and add the best license for your project.

- [x] Choose a methodology versioning and follow.

- [x] Create a roadmap to make clear the course of the project.

- [x] Document your project in the best possible way.

- [x] Describe your Releases clearly and objectively or create a CHANGELOG.md file and do it there.

- [x] Use badges to indicate the status of your project.

- [ ] Configure and add a .editorconfig.

- [ ] When necessary do not hesitate to create a website for your project. Enjoy and publish with github pages.

- [x] Write automated tests

- [x] Integrate your tests a Continuous Integration service.

- [x] Provide your project in the appropriate package manager. (EX: bower, npm, etc...)
